apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pangolin-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pangolin-ingress-controller
subjects:
  - kind: ServiceAccount
    name: pangolin-ingress-controller
    namespace: pangolin-system
